add_library(absyntax_utils STATIC absyntax_utils.cc
                                case_element_iterator.cc
                                function_call_iterator.cc
                                get_datatype_info.cc
                                search_base_type.cc
                                search_il_label.cc
                                spec_init_separator.cc
                                add_en_eno_param_decl.cc
                                debug_ast.cc
                                function_call_param_iterator.cc
                                get_sizeof_datatype.cc
                                search_fb_instance_decl.cc
                                search_varfb_instance_type.cc
                                type_initial_value.cc
                                array_dimension_iterator.cc
                                decompose_var_instance_name.cc
                                function_param_iterator.cc
                                get_var_name.cc
                                search_fb_typedecl.cc
                                search_var_instance_decl.cc
)
